export const RouteConst = {
    MAIN: "/",
    USERS: "users",
    NOT_FOUND_PAGE: "/error",
    USER_ID: ":userId",
    MENTOR: "/",
    ANDRIANA_M: "/anjoanka",
    ANDRIANA_FORM: "/anjoanka/form",
    ANDRIANA_INFO: "/anjoanka/about",
    ANDRIANA_AXIOS: "/anjoanka/axios",
    DANYLO: "/danylo",
    ADMIN: "/admin",
    IhorKurylov: "/IhorKurylov",
    VitrikushIhor: "/VitrikushIhor",
    MARK: "/mark",
    Volodia: "/Volodia",
    VASYLYATSISHIN: "/vasylyatsishin",
    Vitrikush_Ihor_FORM: "/VitrikushIhor/form",
    DANYLO_FORM: "/danylo/form",
    DANYLO_AXIOS: "/danylo/axios",
    Vitrikush_Ihor: "/VitrikushIhor",
    Vitrikush_Ihor_FORM: "/VitrikushIhor/form",
    Vitrikush_Ihor_Axios: "/VitrikushIhor/axios",
    Vitrikush_Ihor_Json_Axios: "/VitrikushIhor/jsonAxios",
    Vitrikush_Ihor_Registered: "/VitrikushIhor/registered",
    Vitrikush_Ihor_Btn_Dz: "/VitrikushIhor/btnDz",
};

export const IhorRoutes = {
    LOGIN: "/login",
};
